<div class="cms-descrp">
    <h2>COMPAÑÍA</h2>
    <h3>FuXion Mejoramos tu vida!</h3>
    <p>Fuxion es una empresa multinacional que ofrece la oportunidad de tener una franquicia master con baja inversión y un poderoso sistema de trabajo, simple y fácil de replicar. Tienes 15 formas de generar ingresos, bonos y utilidades.</p>
    <p>Te invitamos a visitar nuestra página web, y conocer más sobre la ciencia que hay detras de la oportunidad FuXion.</p>
    <ul>
    	<li>Staff Ejecutivo</li>
    	<li>Fusión Nutracéutica</li>
    	<li>Ciencia natural</li>
    	<li>Patentes</li>
    	<li>Comité científico</li>
   	</ul>
   	<div class="nav-social">
   		<a href="https://www.facebook.com/fuxion" class="fb" target="_blank" title="Facebook">Facebook</a>
   		<a href="https://twitter.com/fuxionoficial" class="twt" target="_blank" title="Twitter">Twitter</a>
<!--   		<a href="javascript:;" class="blg" title="Blogger">Blogger</a>-->
   		<a href="https://www.youtube.com/fuxionoficial" class="ytb" target="_blank" title="Youtube">Youtube</a>
   		<a href="javascript:;" class="eml" target="_blank" title="E-Mail">E-Mail</a>
   	</div>
</div>
<div class="cms-img">
	<img src="<?php echo STATIC_URL?>img/element/map.jpg"/>
</div>