<div class="row-well">
    <?php echo $this->partial('_partial/_profile.phtml', $this)?>
    <div class="fx-break"></div>
    
    <div class="fx-descrp">
        <h2>CONTACTAME</h2>
        <?php $this->getMesseger(); ?>
        <p><?php echo $this->businessman['testimony']?></p>
        <form id="frm-contactenos" method="POST"  action="/contact/index">
            <div class="control-group">
              <input type="text" name="txtName" id="txtName" placeholder="Nombre"/>
            </div>
            <div class="control-group">
              <input type="text" name="txtLastName" id="txtLastName" placeholder="Apellidos"/>
            </div>
            <div class="control-group">
              <input type="text" name="txtEmail" id="txtEmail" placeholder="Email"/>
            </div>
            <div class="control-group mb16">
              <textarea name="txaMessage" id="txaMessage" placeholder="Mensaje"></textarea>
            </div>
            <div class="controls">
              <button type="submit" class="btn-fuxion">Enviar</button><a href="#home" class="main-snav btn-lnk">Cancelar</a>
            </div>
        </form>
    </div>
</div>