<div class="row-well">
    <div class="fx-profile">
        <div class="prof-img"><img src="img/element/perfil.jpg" width="208" height="208"/></div>
        <h2 class="prof-name">VICTOR EDUARDO CRUZ MORAN<br>(empresario independiente)</h2>
        <p class="prof-address">51-992787034<br><a href="mailto:alfredovi@gmail.com">alfredovi@gmail.com</a></p>
        <ul class="prof-social">
            <li><a href="javascript:;" title="Twitter" class="twt"></a>TWITTER</li>
            <li><a href="javascript:;" title="Facebook" class="fb"></a>FACEBOOK</li>
            <li><a href="javascript:;" title="Youtube" class="ytb"></a>YOUTUBE</li>
            <li><a href="javascript:;" title="Blog" class="blg"></a>BLOG</li>
        </ul>
    </div>
    <div class="fx-break"></div>
    <div class="fx-descrp">
        <h2>MI TESTIMONIO</h2>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids</p>
    </div>
</div>