<div id="main-slider" class="fix">    
    <div class="slide-main fix2">
        <?php if($this->changeOk) : ?>

        <div class="ctn-confForget">
            <h2>Contraseña Cambiada</h2>
            <p>La contraseña ha sido cambiada correctamente</p>
            <div class="control">
                <a class="btn-lnk" href="/" title="Finalizar">Finalizar</a>
            </div>
        </div>

        <?php else : ?>

        <div class="ctn-forgetPass">
            <h2>Cambiar contraseña</h2>
            <p>Introduzca en los campos, la nueva contraseña a cambiar, luego haga click en Guardar. Luego le confirmaremos que su contraseña ha sido cambiada.</p>
            <?php echo $this->form?>
        </div>

        <?php endif; ?>
    </div>
</div>