<div class="login-cnt">
    <div class="ctn-ilogin">
        <?php if($this->sendOk) : ?>
        <h2 class="fix">Revisa tu email</h2>
        <p>En instantes recibirás un correo electrónico con un link e instrucciones para reestablecer tu contraseña.</p>
        <?php else : ?>
        <h2>Asistente para recuperar contraseña</h2>
        <?php $this->getMesseger();?>
        <div class="frmLogin">
            <?php echo $this->form?>
        </div>
        <?php endif; ?>
        <div class="helpers-cnt">
            <a href="/" title="Volver"><< Volver</a>
        </div>
    </div>
 </div>