<div class="white-bg">
    <?php echo $this->partial('_partial/_siteBar.phtml', $this)?>
    <section class="content">
        <div class="col-product-info">
            <img alt="<?php echo $this->product['desprod']; ?>" src="<?php echo $this->product['picture']; ?>" />
            <h4><?php echo $this->product['shorttext']; ?></h4>
            <div class="btn-fav-cnt">
                <h3>¿Desea Agregar el producto a favoritos?<span>Presionar en la Estrella</span></h3>
                <button><i class="sprites-p star-big"></i></button>
            </div>
        </div>
        <div class="col-product-detail">
            <h2><?php echo $this->product['desprod']; ?></h2>
            <div class="col-two">
                <h3>Contenido Caja:</h3>
                <ul> 
                  <li><?php echo $this->product['desccaja']; ?> </li>
                </ul>
            </div>
            <div class="col-two">
                <h3>Puntos a Ganar:</h3>
                <ul> 
                    <li><i class="sprites-p star"> </i>Puntos Productos: <?php echo $this->product['punprod']; ?></li>
                </ul>
            </div>
            <h3>Precio de Lista <span>(Incluid I.G.V.)</span></h3><span class="precio">S/. <?php echo $this->product['finalPrice']; ?></span>
            <div class="pad-wrapper">
                <table border="0">
                    <?php if (!empty($this->discounts)) : ?>
                    <tr>
                        <th>Normal</th>
                        <?php foreach ($this->discounts as $discount) : 
                            if ($discount['pordesc'] > 0) : ?>
                        <th><?php echo number_format($discount['pordesc']*100, 2, '.', ''); ?>%</th>
                        <?php endif; 
                            endforeach; ?>
                    </tr>
                    <tr>
                        <td>S/. <?php echo $this->product['finalPrice']; ?></td>
                        <?php foreach ($this->discounts as $discount) : 
                            if ($discount['pordesc'] > 0) : ?>
                            <td>S/. <?php echo number_format($this->product['finalPrice']*(1-$discount['pordesc']), 2, '.', ''); ?></td>
                        <?php endif; 
                            endforeach; ?>
                    </tr>
                    <?php endif; ?>
                </table>
                <fieldset>
                    <label>Cantidad</label>
                    <input type="text" maxlength="2" value="12"/>
                    <button class="orange"><i class="sprites-p cart-inv"> </i>Agregar Producto</button>
                </fieldset><span class="warning">* Debe ingresar minimo 1 unid. producto</span>
                <button class="orange center"><i class="sprites-p arrow-boxed"> </i>Ir a carrito de compra</button>
            </div>
        </div>
        <div class="col-product-moreDetail">
            <?php echo $this->product['text']; ?>
            
            <button class="orange center"><i class="sprites-p arrow-boxed"> </i>Ir a carrito de compra</button>
        </div>
    </section>
</div>