<h3 class="admin-title">Banner</h3>
<div class="frm-panel">
    <form method="POST"> 
        <div class="control-group">
            <div class="control">
                <select id="type" name="type" class="select-large">
                    <?php foreach($this->types as $key => $type) : ?>
                    <option value="<?php echo $key; ?>" <?php echo $this->selectedType == $key ? 'selected' : ''; ?>><?php echo $type; ?></option>
                    <?php endforeach; ?>
                </select> 
            </div>
        </div>
        <div class="row-well">
            <div class="ctn-file">
             
                <button id="btnBanner" class="btn-admin btn-file">Agregar Banner<span></span></button>
                <span class="help-iblock w565">*Para agregar un banner, haga click en el botón "Agregar Banner" y luego seleccione la ubicación de la imagen a subir, ordene los banner según lo requiera y luego haga clic en el botón "Guardar cambios".</span>
            </div>
            <h3> <?php echo $this->mensaje; ?>. Las imágenes deben tener las siguientes extensiones PNG,JPG,GIF o JPEG</h3>       
            <div id="ctn-banner" class="row">
                <p class="nd-banner hide">No hay banners en esta categoría</p>
                <ul id="sortBanner" class="sort-banner">
                    <?php foreach($this->banners as $banner) : ?>
                        <li class="li-sbanner">
                            <div class="banner-img">
                                <img src="<?php echo DINAMIC_URL.'banner/'.$banner['carpeta'].'/'.$banner['imagen']; ?>" width="70" height="70" />
                            </div>
                            <div class="banner-desc">
                                <div class="cgroup-inline">
                                    <div class="control-group">
                                        <label class="control-label">Título:</label>
                                        <div class="controls">
                                            <input type="text" name="txtTitulo[<?php echo $banner['idbanner']; ?>]" 
                                                   value="<?php echo $banner['titulo']; ?>"/>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label">Visible:</label>
                                        <div class="controls fix">
                                            <input type="checkbox" value="1" name="chkEstado[<?php echo $banner['idbanner']; ?>]" 
                                                   <?php echo $banner['vchestado'] == 'A' ? 'checked="checked"' : ''; ?> />
                                        </div>
                                    </div>
                                </div>
                                <div class="control-group last">
                                    <label class="control-label">Link:</label>
                                    <div class="controls">
                                        <input type="text" name="txtLink[<?php echo $banner['idbanner']; ?>]" 
                                               value="<?php echo $banner['url']; ?>" />
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="txtImagen[<?php echo $banner['idbanner']; ?>]" value="<?php echo $banner['imagen']; ?>" />
                            <a class="ic-close" href="javascript:;" title="Cerrar"></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="control">
                    <button type="submit" class="btn-admin">Guardar cambios</button>
                </div>
            </div>
        </div>
    </form>
</div>
<script id="tplBanner" type="text/template">
<li class="li-sbanner">
	<div class="banner-img">
		<img src="{{= source}}" width="70" height="70" />
	</div>
	<div class="banner-desc">
		<div class="cgroup-inline">
			<div class="control-group">
				<label class="control-label">Título:</label>
				<div class="controls">
					<input type="text" name="txtTitulo[{{= code}}]" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Visible:</label>
				<div class="controls fix">
					<input type="checkbox" checked="checked" value="1" name="chkEstado[{{= code}}]" />
				</div>
			</div>
		</div>
		<div class="control-group last">
			<label class="control-label">Link:</label>
			<div class="controls">
				<input type="text" name="txtLink[{{= code}}]" />
			</div>
		</div>
	</div>
	<input type="hidden" name="txtImagen[{{= code}}]" value="{{= nombre}}" />
	<a class="ic-close" href="javascript:;" title="Cerrar"></a>
</li>
</script>