<div class="white-bg ctn-pendingpay">
    <?php echo $this->partial('_partial/_siteBar.phtml', $this)?>
    <header class="head-car">
        <h2>Pagos Pendientes</h2>
        <p class="descDir">A continuación se muestran la lista de los pedidos, pendientes de Pago.<span></span></p>
    </header>
    <table>
        <thead>
            <tr>
                <th>Código Pedido</th>
                <th>Fecha de Compra</th>
                <th>Enviado a</th>
                <th>Método de Pago</th>
                <th>Monto de Pago</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->orders as $order) : ?>
            <tr>
                <td><?php echo $order['idpedi']; ?></td>
                <td><?php echo $order['fecpedi'].' '.$order['horpedi']; ?></td>
                <td><?php echo $order['ubidenv']; ?></td>
                <td><?php echo $order['mediopago']; ?></td>
                <td><?php echo $this->businessman['simbolo'].' '.$order['precio']; ?></td>
                <td><a href="/product/pending-payment-detail/id/<?php echo $order['idpedi']; ?>" title="Ver Detalle">Detalle</a><a href="javascript:;" title="Eliminar">Eliminar</a></td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>