<!doctype html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]> <html lang="es"> <![endif]-->
<?php echo $this->render("admin-challenge/head.phtml"); ?>
<body>
    <?php echo $this->render("admin-challenge/header.phtml"); ?>
    <div id="wrapper" class="row">
        <?php 
            if($this->action != 'detail-progress'){
                echo Zend_Auth::getInstance()->hasIdentity() ? $this->render("admin-challenge/leftbar.phtml") : '';
            }
        ?>
        <?php echo $this->layout()->content; ?>
    </div>
    <script type="text/javascript">
        var gaiSelected = [];
        var yOSON ={
            "modulo":"<?php echo $this->module?>",
            "controller":"<?php echo $this->controller?>",
            "action":"<?php echo $this->action?>",
            "baseHost":"<?php echo SITE_URL?>",
            "statHost":"<?php echo STATIC_URL?>",
            "statVers":"?<?php echo SITE_VERSION; ?>",
            <?php foreach ($this->yosonVars as $key => $value) : 
                 echo '"'.$key.'":'.$value.', '; 
                endforeach; 
                echo '"min":"","AppCore":{},"AppSandbox":{},"AppSchema":{"modules":{},"requires":{}'
                ?>  
            }
          };
      </script>
      <script type="text/javascript" src="<?php echo STATIC_URL?>js/libs/framework.js?v=<?php echo SITE_VERSION; ?>"></script>
      <script type="text/javascript" src="<?php echo STATIC_URL?>js/application/yoson.js?v=<?php echo SITE_VERSION; ?>"></script>
      <script type="text/javascript" src="<?php echo STATIC_URL?>js/modules/adminDesafio.js?v=<?php echo SITE_VERSION; ?>"></script>
      <script type="text/javascript" src="<?php echo STATIC_URL?>js/application/schemas/mADesafio.js?v=<?php echo SITE_VERSION; ?>"></script>
      <script type="text/javascript" src="<?php echo STATIC_URL?>js/application/appLoad.js?v=<?php echo SITE_VERSION; ?>"></script>
</body>
