<!doctype html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]> <html lang="es"> <![endif]-->
<?php echo $this->render("office/head.phtml"); ?>
<body>
    <?php echo $this->render("office/header.phtml"); ?>
    <div id="wrapper">
        <?php echo $this->layout()->content; ?>
    </div>
    <?php echo $this->render("office/footer.phtml"); ?>
</body>
