<footer>
  <div class="box-center">
    <nav class="foot-menu"><a href="<?php echo SITE_URL ; ?>index/condition" title="Estado">estado</a><a href="<?php echo SITE_URL ; ?>index/consume" title="Mis consumos">mis consumos</a><a href="<?php echo SITE_URL ; ?>index/progress" title="Avances">avances</a><a href="<?php echo SITE_URL ; ?>index/mentor" title="Mentor">mentor</a><a href="<?php echo SITE_URL ; ?>index/contact" title="contáctenos">contáctenos</a></nav>
    <p>Copyrigth © 2013 Prolife Biotech. Todos los derechos reservados</p>
  </div>
</footer>