<div id="main-slider" class="fix">
    <div class="slide-main">
        <?php $this->getMesseger();?>

        <?php if($this->sendOk) : ?>

        <div class="ctn-confForget">
            <h2>Revisa tu email</h2>
            <p>En instantes recibirás un correo electrónico con un link e instrucciones para reestablecer tu contraseña.</p>
        </div>    

        <?php else : ?>
        
        <div class="ctn-forgetPass">
            <h2>Asistente para recuperar contraseña</h2>
            <p>Introduzca su dirección de correo electrónico asociado a su cuenta, luego haga click en Siguiente. Te enviaremos por correo electrónico un enlace a una página donde usted puede cambiar facilmente su contraseña.</p>
            <?php echo $this->form?>
        </div>
        
        <?php endif; ?>
        <a title="Atrás" href="/account" class="btn-back"></a>
    </div>
</div>