<div id="main-slider" class="fix">
  <div class="slide-main fix2">
    <div class="ctn-cuentanav">
      <ul class="cuenta-nav">
        <li class="active"><a href="/account/my-account" title="Mis Datos">MIS DATOS</a></li>
        <li><a href="/account/order-list" title="Mis Pedidos">MIS PEDIDOS</a></li>
        <li><a href="/account/logout" title="Desconectarse">DESCONECTARSE</a></li>
      </ul>
    </div>
    <div class="cuenta-det">
      <h2>EDITAR INFORMACIÓN DE CUENTA</h2>
      <?php echo $this->form?>
    </div>
  </div>
</div>