<table style="margin:0 auto; padding:0;font-family:Arial, Helvetica, sans-serif;" width="650" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr>
        <td bgcolor="#fbfbfb">
            <table style="margin:0 auto" width="602" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <td style="height:54px">&nbsp;</td>
                </tr>
                <tr>
                    <td height="52" align="center" valign="top">
                            <h1 style="font-family:Arial,sans-serif;font-size:28px;font-weight:700;color:#696969;text-align:center;line-height:28px;margin:0">Confirmación de Compra</h1>
                    </td>
                </tr>
                <tr>
                    <td>
                	<table style="margin:0 auto;border:1px solid #c7c7c6;" width="600"  align="center" cellpadding="0" cellspacing="0">
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:26px">&nbsp;</td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px">
                                    <h2 style="text-align:center;margin:0;font-size:24px;font-weight:400;font-family:Arial, Helvetica, sans-serif;color:#db8f1b">!Gracias por su compra!</h2>
                                </td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:20px">&nbsp;</td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px">
                                    <h3 style="text-align:center;margin:0;color:#8a8a8a;font-family:Arial,Helvetica,sans-serif;font-size:16px;font-weight:400">Hola <?php echo $this->mailData['name'].' '.$this->mailData['lastname']?></h3>
                                </td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:12px">&nbsp;</td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px">
                                    <p style="margin:0;font-size:13px;line-height:24px;color:#b6bbba;text-align:center">Su pedido #<?php echo $this->mailData['idOrder']?> ha sido procesado correctamente y será enviado a la dirección <?php echo $this->mailData['address']?>. El detalle de tu pedido es:</p>
                                </td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:28px">&nbsp;</td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px">
                                    <table width="510" cellspacing="0" cellpadding="0" align="center" style="margin:0 auto">
                                        <thead>
                                          <tr>
                                            <th style="text-align:center;background:#c4c4c4;color:#FFF;font-size:13px;padding:8px;font-family:Arial,sans-serif;width:177px">Nombre del Producto</th>
                                            <th style="text-align:center;background:#c4c4c4;border-left:1px solid #b1b1b1;color:#FFF;font-size:13px;padding:8px;font-family:Arial,sans-serif;width:62px">Cantidad</th>
                                            <th style="text-align:center;background:#c4c4c4;border-left:1px solid #b1b1b1;color:#FFF;font-size:13px;padding:8px;font-family:Arial,sans-serif;width:102px">Precio Unitario</th>
                                            <th style="text-align:center;background:#c4c4c4;border-left:1px solid #b1b1b1;color:#FFF;font-size:13px;padding:8px;font-family:Arial,sans-serif;width:102px">Precio Final</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($this->mailData['cart']['items'] as $item) : ?>
                                            <tr>
                                                <td style="font-size:12px;font-family:Arial,sans-serif;padding:8px;border-bottom:1px solid #FFF;background:#f6f6f6;width:177px">
                                                    <a style="text-decoration:none;color:#db8f1b" href="javascript:;" title="Biopro + Sport" target="_blank"><?php echo $item['name']; ?></a>
                                                </td>
                                                <td style="text-align:center;font-size:12px;font-family:Arial,sans-serif;padding:8px;border-bottom:1px solid #FFF;background:#f6f6f6;width:62px"><?php echo $item['quantity']; ?></td>
                                                <td style="text-align:center;font-size:12px;font-family:Arial,sans-serif;padding:8px;border-bottom:1px solid #FFF;background:#f6f6f6;width:102px"><?php echo $this->mailData['symbol'].' '.$item['price']; ?></td>
                                                <td style="text-align:center;font-size:12px;font-family:Arial,sans-serif;padding:8px;color:#db8f1b;border-bottom:1px solid #FFF;background:#f6f6f6;width:102px"><?php echo $this->mailData['symbol'].' '.$item['subTotal']; ?></td>
                                            </tr>
                                            <?php endforeach; ?>
                                            <tr>
                                              <td colspan="2" style="width:272px">&nbsp;</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px">Subtotal</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px"><?php echo $this->mailData['symbol'].' '.$this->mailData['cart']['subTotal'];?> </td>
                                            </tr>
                                            <tr>
                                              <td colspan="2" style="width:272px">&nbsp;</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px">Flete</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px"><?php echo $this->mailData['symbol'].' '.$this->mailData['cart']['shipPrice'];?> </td>
                                            </tr>
                                            <tr>
                                              <td colspan="2" style="width:272px">&nbsp;</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px">Impuesto (<?php echo $this->mailData['cart']['iva'];?> %)</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px"><?php echo $this->mailData['symbol'].' '.$this->mailData['cart']['igvTotal'];?> </td>
                                            </tr>
                                            <tr>
                                              <td colspan="2" style="width:272px">&nbsp;</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px">TOTAL</td>
                                              <td style="padding:8px;text-align:center;color:#FFF;font-size:12px;font-family:Arial,sans-serif;background:#db8f1b;width:102px"><?php echo $this->mailData['symbol'].' '.$this->mailData['cart']['total'];?> </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:28px">&nbsp;</td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px">
                                    <p style="margin:0;font-size:13px;line-height:24px;color:#b6bbba;text-align:center">Le agradecemos muy gentilmente su compra.</p>
                                </td>
                            </tr>
                            <tr style="background:#FFF">
                                <td style="padding:0 44px;height:26px">&nbsp;</td>
                            </tr>
                    </table>
                </td>
       	  </tr>
          <tr>
          	<td style="height:26px">&nbsp;</td>
          </tr>
          <tr>
          	<td align="center" valign="middle">
            	<a href="javascript:;" target="_blank" title="Fuxion">
            		<img src="<?php echo $this->mailData['imgFuxion']?>" width="175" border="0" height="69" alt="Fuxion" />
                </a>
            </td>
          </tr>
          <tr>
          	<td style="height:54px">&nbsp;</td>
          </tr>
       </table>
    </td>
  </tr>
</table>