  <div id="wrapper">
    <div class="row content-contact">
      <div class="info-contact">
        Av. Javier Prado Oeste 1856 San Isidro<br /> Lima -  Peru <br />Tel.: 511 5139100
      </div>
      <form id="frmContact" name="frmContact" method="post" action="" class="frm-contact">
        <div class="frm-group">
          <label for="txtName" class="control-label">NOMBRE</label>
          <div class="frm-control">
            <input type="text" id="txtName" name="nombre" placeholder="Nombres y Apellidos"/>
          </div>
        </div>
        <div class="frm-group">
          <label for="txtEmail" class="control-label">EMAIL</label>
          <div class="frm-control">
            <input type="text" id="txtEmail" name="correo" placeholder="Correo Electrónico"/>
          </div>
        </div>
        <div class="frm-group">
          <label for="txtMessage" class="control-label">CONSULTA</label>
          <div class="frm-control">
            <textarea type="textarea" id="txtMessage" name="mensaje" placeholder="Escriba aquí su consulta"></textarea>
          </div>
        </div>
        <div class="frm-group row">
          <button type="submit" id="sbmSend" title="Enviar" class="btn">Enviar</button>
        </div>
      </form>
    </div>
  </div>