<form method="POST" id="frm-forgetPass">
    <div class="control-group">
        <label class="control-label" for="emaempr"><i class="sprites icon-email"></i></label>
        <div class="controls">
            <?php echo $this->element->tokenHash->renderViewHelper(); ?> 
            <?php echo $this->element->emaempr->renderViewHelper(); ?>
        </div>
    </div>
    <div class="control-group">
        <div class="ctn-captcha">
            <?php echo $this->element->captcha; ?>
            <a href="javascript:;" title="Actualizar" class="btn-refresh"><i class="sprites icon-refresh"></i></a>
        </div>
    </div>
    <div class="control mt20">
        <button type="submit" class="btn-entrar">ENVIAR</button>
    </div>
</form>