<h3 class="admin-title">Productos</h3>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Productos</h2>
    </div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Código</th>				
                <th>Nombre</th>
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>