<script type="text/javascript">
    function AgregarCampos(){
        $("#campos").append('<tr><td class="controls"><input name="alternativa[]" type="text" /></td></tr>');
    }
</script>
<h3 class="admin-title"><?php echo $this->element->getView()->titulo?></h3>
<div class="ctn-back">
    <a title="Volver al listado de Encuestas" href="/quiz">« Volver al listado de Encuestas</a>
</div>
<div class="frm-panel">
    <form id="frm-article" action="<?php echo $this->element->getView()->action?>" 
          method="post" Enctype="multipart/form-data">        
        <div class="control-group">
            <label class="control-label" for="pregunta">Pregunta:</label>
            <div class="controls">
                <?php echo $this->element->pregunta; ?>
                <?php echo $this->element->idencuesta; ?>
            </div>
	</div>
        <div class="control-group">
            <label class="control-label" for="vchalternativa">Alternativas:</label>
            <div class="controls">     
      <div id="campos">
       <?php if($this->element->getView()->titulo=='Editar Encuesta'){
        foreach($this->element->getView()->QuizType as  $value):?>
      <input name="idtencuestaalr[]" type="hidden" value="<?php echo $value['idtencuestaalr']; ?>" />
      <input name="alternativa[]" type="text" value="<?php echo $value['alternativa']; ?>" /></br></br>
	<?php endforeach;}else
       {?><input type="button" value="Añadir Alternativa" onclick="AgregarCampos()"/></br></br><?php } ?>
       </div>
            </div>
	</div>
        <div class="control-group">
               <label class="control-label" for="descripcion">Descripción:</label>
            <div class="controls">
                <?php echo $this->element->descripcion; ?>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="vchestado">Activo:</label>
            <div class="controls">
                <?php echo $this->element->vchestado; ?>
            </div>
	</div>
        
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit"><?php echo $this->element->getView()->submit?></button>
            </div>
	</div>
   </form>
</div>