<h3 class="admin-title"><?php echo $this->element->getView()->titulo?></h3>
<div class="ctn-back">
    <a title="Volver al listado de Roles" href="/role">« Volver al listado de Roles</a>
</div>
<div class="frm-panel">

    <form id="frm-article" action="<?php echo $this->element->getView()->action?>" 
          method="post" Enctype="multipart/form-data">

        
        <div class="control-group">
            <label class="control-label" for="desrol">Descripción:</label>
            <div class="controls">
                <?php echo $this->element->desrol; ?>
                <?php echo $this->element->idrol; ?> 
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="acls">Privilegios:</label>
            <div class="controls">
                <?php echo $this->element->acls; ?>
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="state">Activo:</label>
            <div class="controls">
                <?php echo $this->element->state; ?>
            </div>
	</div>
        
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit"><?php echo $this->element->getView()->submit?></button>
            </div>
	</div>
   </form>
</div>