<h3 class="admin-title"><?php echo $this->element->getView()->titulo?></h3>
<div class="ctn-back">
    <a title="Volver al listado de Videos" href="/video">« Volver al listado de Videos</a>
</div>
<div class="frm-panel">

    <form id="frm-article" action="<?php echo $this->element->getView()->action?>" 
          method="post" Enctype="multipart/form-data">

        <div class="control-group">
            <label class="control-label" for="codtvideo">Tipo:</label>
            <div class="controls">
                <?php echo $this->element->codtvideo; ?>
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="url">URL:</label>
            <div class="controls">
                <?php echo $this->element->url; ?>
                <?php echo $this->element->idvideo; ?> 
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="titulo">Título:</label>
            <div class="controls">
                <?php echo $this->element->titulo; ?>
            </div>
	</div>
        
        <div class="control-group">
            <label class="control-label" for="descripcion">Descripción:</label>
            <div class="controls">
                <?php echo $this->element->descripcion; ?>
            </div>
        </div>
        
        
        <div class="control-group">
            <label class="control-label" for="vchestado">Activo:</label>
            <div class="controls">
                <?php echo $this->element->vchestado; ?>
            </div>
	</div>
        
	<div class="control-group last">
            <div class="control">
                <button class="btn-admin" type="submit"><?php echo $this->element->getView()->submit?></button>
            </div>
	</div>
   </form>
</div>