<h3 class="admin-title">Catálogo</h3>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de catálogo</h2>
    </div>
    <div class="datatable-header"><div id="datatable_filter" class="dataTables_filter"></div></div>
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display dataTable">
        <thead>
            <tr>
                <th>Nro.</th>				
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php $count = 0; foreach($this->catalogs as $catalog) : $count++;?>
            <tr>				
                <td class="center"><?php echo $count.'.'; ?></td>
                <td><?php echo $catalog['destpro']; ?></td>
                <td class="center"><a href="/catalog/products/<?php echo $catalog['slug']; ?>">Ver Lista</a></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>