<h3 class="admin-title">Catálogo</h3>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Agregar Producto al catálogo <?php echo $this->selectedCatalog['destpro']; ?></h2>
        <a href="/catalog/products/<?php echo $this->selectedLine['slug']; ?>" class="btn-admin btn-file">Regresar</a>
    </div>
    
    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Código</th>				
                <th>Nombre</th>
                <th>Estado</th>
                <th>Agregar</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>