<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <title>Fuxion - Empresario Independiente</title>
  <meta name="title" content="Fuxion - Empresario Independiente"/>
  <meta name="description" content="Fuxion, Empresario Independiente"/>
  <meta name="keywords" content="fuxion, empresario, independiente"/>
  <meta name="author" content="onlinestudioproductions.com"/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="language" content="es"/>
  <meta name="robots" content="noindex"/>
  <link href="<?php echo STATIC_URL?>img/fuxion.gif" rel="image_src" type="image/jpeg"/>
  <link href="<?php echo STATIC_URL?>img/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <link href="<?php echo STATIC_URL?>img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link type="text/css" rel="stylesheet" href="<?php echo STATIC_URL; ?>css/desafio.css?v=<?php echo SITE_VERSION; ?>"/>
  <!--[if lt IE 9]>
    <script src="<?php echo STATIC_URL; ?>js/libs/html5shiv.js"></script>
  <![endif]-->
</head>