<form class="frmLoginAdmin" id="frm-login" method="POST" action="/login">
    <h2>INGRESA A TU CUENTA</h2>
    <div class="frm-group">
        <label for="txtUsername" class="control-label">Username:</label>
        <div class="frm-control">
            <input type="text" name="txtUsername" id="txtUsername" />
        </div>
    </div>
    <div class="frm-group">
        <label for="txtPassword" class="control-label">Password:</label>
        <div class="frm-control">
            <input type="password" name="txtPassword" id="txtPassword" />
        </div>
    </div>
    <div class="frm-group">
        <div class="control">
            <button id="btnLogin" type="submit" class="btn">Ingresa</button>
        </div>
    </div>
</form>