<form id="frmRegister" method="POST">
    <div class="row">
        <h2>DATOS PERSONALES</h2>
        <div class="step2-left">
            <div class="control-group">
                <?php echo $this->element->name->renderViewHelper(); ?>
                <?php echo $this->element->idcliper->renderViewHelper(); ?> 
                <?php echo $this->element->tokenHash->renderViewHelper(); ?> 
            </div>
            <div class="control-group">
                <?php echo $this->element->lastname->renderViewHelper(); ?>
            </div>
            <div class="control-group">
                <?php echo $this->element->email->renderViewHelper(); ?>
            </div>
            <div class="control-group">
                <?php echo $this->element->password->renderViewHelper(); ?>
            </div>
            <div class="control-group">
                <?php echo $this->element->confirm->renderViewHelper(); ?>
            </div>
            <div class="control-group last">
                <label class="control-label fix">Género:</label>
                <div class="controls iopinline">
                    <?php echo $this->element->gender->renderViewHelper(); ?>
                </div>
            </div>
        </div>
        <div class="step2-right">
            <div class="control-group">
                <label class="control-label fix">Estado Civil:</label>
                <div class="controls iopinline">
                    <?php echo $this->element->civilstate->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <?php echo $this->element->ndoc->renderViewHelper(); ?>
            </div>
            <div class="control-group">
                <?php echo $this->element->birthdate->renderViewHelper(); ?>
            </div>
            <div class="control-group last">
                <div class="ctn-captcha">
                     <?php echo $this->element->captcha; ?>
                    <a href="javascript:;" class="btn-refresh">Actualizar<span></span></a>
                    <span class="decorCaptcha"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="control">
        <button id="submitRegisterJoined" name="submitRegisterJoined" type="submit"  class="btn-lnk">Guardar</button>
    </div>
</form>