<form method="POST" class="frm-forgetPass">
    <div class="control-group">
        <?php echo $this->element->tokenHash->renderViewHelper(); ?> 
        <?php echo $this->element->email->renderViewHelper(); ?>
    </div>
    <div class="control-group">
        <div class="ctn-captcha">
            <?php echo $this->element->captcha; ?>
            <a href="javascript:;" class="btn-refresh">Actualizar<span></span></a>
            <span class="decorCaptcha"></span>
        </div>
    </div>
    <div class="control">
        <button type="submit" class="btn-lnk">Siguiente</button>
    </div>
</form>