<form method="POST">
        <div class="control-group">
            <?php echo $this->element->tokenHash->renderViewHelper(); ?> 
            <?php echo $this->element->password->renderViewHelper(); ?>
        </div>
        <div class="control-group">
            <?php echo $this->element->confirm->renderViewHelper(); ?>
        </div>
    <div class="control">
        <button type="submit" class="btn-lnk">Guardar</button>
    </div>
</form>