<div class="white-bg fix">
    <?php echo $this->partial('_partial/_siteBar.phtml', $this)?>
    
    <?php if(count($this->itemList)>0){ ?>
    <div class="fullCar">
        <header class="head-car">
            <h2>CARRITO DE COMPRA</h2>
            <p>Tienes <i class="sprites-p cart-big"></i>  <strong id="descQProd"><?php echo count($this->itemList); ?></strong> productos en tu carro de compras </p>
        </header>
        <form method="POST">
            <table border="0" class="tbl-carrito">
                <thead>
                    <tr>
                        <th class="tdImg"></th>
                        <th class="tdProduct">Productos</th>
                        <th class="tdCant">Cantidad</th>
                        <th class="tdPoints">Puntos</th>
                        <?php /*<th class="tdPeso">Peso Neto</th> */ ?>
                        <th class="tdPrice">Precio Unitario</th>
                        <th class="tdSubTotal">Sub Total</th>
                        <th class="tdAction1"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->itemList as $item) : ?>
                   <tr>
                       <td class="tdImg"><img alt="<?php echo $item->getProduct()->getName(); ?>" width="90" height="80" src="<?php echo $item->getProduct()->getUrlPicture(); ?>" /></td>
                       <td class="tdProduct">
                           <h2>
                               <a href="<?php echo $this->url(array('slug' =>$item->getProduct()->getSlug()), 'productDetail'); ?>"> 
                               <?php echo $item->getProduct()->getName(); ?>
                               </a>
                           </h2>
                           <?php $bDescription = $item->getProduct()->getBoxDescription();
                           if (!empty($bDescription)) : ?>
                                <p>Caja (<?php echo $bDescription; ?>)</p>
                           <?php endif; ?>
                           <h3><?php echo $item->getProduct()->getPoints(); ?> Puntos</h3>
                           <?php if ($item->getProduct()->getEnableDiscount() == 0) : ?>
                                <p class="tbl-prodinfo">*Este producto no esta sujeto a descuentos</p>
                           <?php endif; ?>
                           
                       </td>
                       <td class="tdCant">
                            <input data-discount="<?php echo $item->getProduct()->getEnableDiscount(); ?>" 
                                   data-points="<?php echo $item->getProduct()->getPoints(); ?>" 
                                   data-price="<?php echo ((1 + $this->iva) *$item->getProduct()->getPrice()); ?>" class="inptcant" id="txtcant" name="txtcant[<?php echo $item->getProduct()->getId(); ?>]" type="text" maxlength="3" value="<?php echo $item->getQuantity(); ?>"/>
                       </td>
                       <td class="tdPoints" ><?php echo $item->getItemPoints(); ?></td>
                       <?php /* <td class="tdPeso"><?php echo $item->getItemWeight(); ?> KG</td> */ ?>
                       <td class="tdPrice"><?php echo $this->businessman['simbolo']; ?> <?php echo number_format((1 + $this->iva) * $item->getProduct()->getPrice(), 2, '.', ''); ?></td>
                       <td class="tdSubTotal"><?php echo $this->businessman['simbolo']; ?> <?php echo number_format((1 + $this->iva) * $item->getSubTotal(), 2, '.', ''); ?></td>
                       <td class="tdAction1"> <a href="javascript:;" data-id="<?php echo $item->getProduct()->getId(); ?>" class="sprites-p btn-close-red"></a></td>
                   </tr>
                   <?php endforeach; ?>
                </tbody>
            </table>
            <div class="row">
                <div class="cart-note">
                    <?php if ($this->pointsToNextDiscount != 0) : ?>
                    <h4>Nota:</h4>
                        <?php if ($this->hasDiscount) : ?>
                        <p>Te falta <?php echo $this->pointsToNextDiscount; ?> puntos más para alcanzar un descuento de <?php echo $this->nextDiscount; ?>%.</p>
                        <?php else : ?>
                        <p>Te faltan <?php echo $this->pointsToNextDiscount; ?> puntos más para aplicar a los descuentos.</p>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <table class="tbl-payDetail">
                    <tbody>
                        <tr>
                            <td class="tdPoints">Pts <span id="totalPts"><?php echo $this->points; ?></span></td>
                            <?php /*<td>Peso: <?php echo $this->totalWeight; ?> Kg</td> */?>
                            <td class="tdPrice">Sub Total:</td>
                            <td class="tdSubTotal"><?php echo $this->businessman['simbolo']; ?> <span id="subTotal"><?php echo $this->total; ?></span></td>
                        </tr>
                        <tr>
                            <td class="tdPoints">&nbsp;</td>
                            <?php /*<td>&nbsp;</td>*/?>
                            <td class="tdPrice">- Descuento(<span id="percentDis"><?php echo $this->discountP; ?></span>%):</td>
                            <td class="tdSubTotal"><?php echo $this->businessman['simbolo']; ?> <span id="totalDis"><?php echo $this->discount; ?></span></td>
                        </tr>
                        <tr class="totalpDetail">
                            <td class="tdPoints">&nbsp;</td>
                            <?php /*<td>&nbsp;</td>*/?>
                            <td class="tdPrice">TOTAL:</td>
                            <td class="tdSubTotal"><?php echo $this->businessman['simbolo']; ?> <span id="totalCart"><?php echo $this->totalDiscount; ?></span></td>
                        </tr>
                    </tbody>
                </table>
                <div class="alg-right ptb14">
                    <button class="btn-orange" type="submit">IR A DIRECCIÓN DE ENVÍO</button>
                </div>

            </div>
        </form>
        <?php if (!empty($this->discounts)) : ?>
        
        <div id="tblDiscount" class="<?php echo $this->hasDiscount ? '' : 'hide' ?>">
        <p class="pdiscount">Descuento por puntos de compra en volumen:</p>
        <table border="0" class="tbl-discount">
            <tbody>
                <tr>
                    <td>Descuentos por puntos</td>
                    <?php foreach ($this->discounts as $discount) : ?>
                    <td><?php echo $discount['pindesc']; ?> - <?php echo $discount['pfidesc']; ?> Pts</td>
                    <?php endforeach; ?>
                </tr>
                <tr>
                    <td>Descuento Total</td>
                    <?php foreach ($this->discounts as $discount) : ?>
                        <td><?php echo number_format($discount['pordesc']*100, 2, '.', ''); ?> %</td>
                    <?php endforeach; ?>
                </tr>
            </tbody>
        </table>
        <?php endif; ?>
        <p class="obs-info">(*) El descuento sera aplicable solo a los productos puntuables (Productos exclusivos a descuento: Merchandising, auxiliares de venta, etc.). Tiene algunas excepciones.</p>
        </div>
        <div class="pt24">
            <a class="btn-orange" href="javascript:;" title="Seguir Comprando">SEGUIR COMPRANDO</a>
        </div>
    </div>
    <?php } ?>
    <div class="emptyCar <?php if(count($this->itemList)>0){ echo "hide";} ?>">
        <header class="head-car">
            <h2>CARRITO DE COMPRA</h2>
        </header>
        <p>Su carrito esta vacío, diríjase a la tienda para iniciar su compra. Buena Suerte!</p>
        <div class="pt24 alg-center">
            <a class="btn-orange" href="/product" title="Seguir Comprando">COMPRAR EN LA TIENDA</a>
        </div>
    </div>
</div>