<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <title>Administrador Fuxion</title>
  <meta name="title" content="Administrador Fuxion"/>
  <meta name="description" content="Administrador Fuxion"/>
  <meta name="keywords" content="administrador, fuxion, prolife"/>
  <meta name="author" content="onlinestudioproductions.com"/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="language" content="es"/>
  <meta name="robots" content="noindex"/>
  <link href="<?php echo STATIC_URL?>admin/img/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <link href="<?php echo STATIC_URL?>admin/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link type="text/css" rel="stylesheet" href="<?php echo STATIC_URL?>css/admin.css?v=<?php echo SITE_VERSION; ?>"/>
  <link href='http://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css' />
  <!--[if lt IE 9]><script src="<?php echo STATIC_URL?>js/libs/html5shiv.js"></script><![endif]-->
</head>
