<div class="white-bg">
	<div class="row ptb30">
		<div class="topNegocio row">
			<h1 class="titfx lm10">Mi Negocio</h1>
			<ul class="navBar">
				<li><a href="../business">MIS INDICADORES<span></span></a></li>
				<li><a href="red">MI RED<span></span></a></li>
				<li><a href="consumo">MI CONSUMO<span></span></a></li>
				<li><a href="afiliacion" class="active">AFILIACIÓN<span></span></a></li>
				<li><a href="comisiones">MIS COMISIONES<span></span></a></li>
			</ul>
			<!--
			<div class="calSelect">
				
				<div class="calendar">
					
				</div>
				<div class="calSelector">
					<h4>SEMANA</h4>
					<select name="semana" id="">
						<option value="">10 - 2014</option>
						<option value="">9 - 2014</option>
						<option value="">8 - 2014</option>
						<option value="">7 - 2014</option>
						<option value="">6 - 2014</option>
					</select>
				</div>

				<div class="semaforo">
					
				</div>
			-->
			</div>
		</div>
		<div class="row stepsMembership">
			<ul>
				<li class="active"><span>1</span>Posición</li>
				<li><span>2</span>Datos</li>
				<li><span>3</span>Producto</li>
				<li><span>4</span>Envio</li>
				<li><span>5</span>Pago</li>
			</ul>
			<span class="bgLine"></span>
		</div>
		<div class="row stepsMemberShip-desc">
			<div class="widget-cnt border slider">
				<div class="titHint">
					<h3 class="titfx" > PASO 1: DEFINIR LA POSICIÓN EN LA RED BINARIA</h3>
					<div class="stepHint">
						Indique el colocador
					</div>
				</div>
				<div class="stepSplit">
					<div class="s1"></div>
				</div>
				<div class="description">
					<div class="descSearch">
						<div class="descText">
							Si no conoce el código del colocador indicador <br/>puedes clsikear el botón de abajo <br/>para ubicarlo
						</div>
						<!--
						<div class="socButton">
							<div class="icon"></div>
							<div class="text">BUSCAR CÓDIGO SOCIO</div>
						</div>
						-->
					</div>
					<div class="widget"></div>
				</div>
			</div>
		</div>
		
	</div>
</div>
