<div class="content-desafio">
    <?php if(!$this->stateBusinessman):?>
    <div class="alert-red">
        Estimado empresario, usted no puede inscribirse por que se encuentra desactivado.
    </div>
    <?php endif;?>
  <div class="img-step-home">
      <img src="<?php echo STATIC_URL; ?>img/desafio/elements/home2desafio4.jpg" 
            alt="Desafío Fuxion" width="695" height="435"/>
  </div>
  <h2 class="title-steps">¿Cómo participar?</h2>
  <ul class="list-numbers">
    <li> Inscribirse en ifuXion, junto con un mentor que apoye al concursante.
    <li> Seguir un plan de alimentación saludable, complementado con productos FuXion del Sistema para Bajar de Peso y Medidas durante 15 semanas (105 días).</li>
    <li> Actualizar la información personal semanalmente durante las 12 primeras semanas.</li>
    <li> Registrar el progreso con evidencias (winchas de peso, fotos, videos) por lo menos una vez a la semana, durante las 12 semanas de pre-calificación. Las siguientes 3 semanas deberán ser corroboradas en las oficinas de FuXion, en una entrevista personal.</li>
    <li> Mantenerse activo durante las 15 semanas y comprar productos de la línea Bajar de Peso y medidas.</li>
    <li> Con la información y evidencias de las primeras 12 semanas construir un caso/testimonio y presentarlo en un video o flash en las oficinas FuXion para su pre-calificación.</li>
    <li> Mantener el peso alcanzado por las siguientes 3 semanas de pre-calificacíon, para concursar por el premio.</li>
    <li> De ganar el concurso, el ganador deberá mantener el peso logrado hasta el viaje.</li>    
  </ul><a href="<?php echo SITE_URL; ?>inscription/step-one-a" title="Inicia tu reto ya" class="btn-green btn-inscription btn-greenHome">¡ INICIA TU RETO YA !</a>
</div>