<h3 class="admin-title">Usuarios</h3>
<div class="frm-panel">
    <div class="frm-head">
        <h2><span class="icTable"></span>Listado de Usuarios</h2>
        <a class="btn-admin" title="Agregar Nuevo" href="/user/new">Agregar Nuevo</a>
    </div>


    <table cellspacing="0" cellpadding="0" border="0" id="datatable" class="display">
        <thead>
            <tr>
                <th>Nombre</th>				
                <th>E-Mail</th>				
                <th>Estado</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>