<h3 class="admin-title">Usuarios</h3>
<div class="ctn-back">
    <a title="Volver al listado de Usuarios" href="/user">« Volver al listado de Usuarios</a>
</div>
<div class="frm-panel">
    <div class="control-group">
        <label class="control-label" for="txtLogin">Login:</label>
        <div class="controls">
            <input type="text" id="txtLogin" name="txtLogin">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="txtPass">Password:</label>
        <div class="controls">
            <input type="password" id="txtPass" name="txtPass">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="txtName">Nombre:</label>
        <div class="controls">
            <input type="text" id="txtName" name="txtName">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="txtApePat">Apellido Paterno:</label>
        <div class="controls">
            <input type="text" id="txtApePat" name="txtApePat">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="txtName">Apellido Materno:</label>
        <div class="controls">
            <input type="text" id="txtApeMat" name="txtApeMat">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label lbloption" for="chckActive">Activo:</label>
        <div class="controls">
                <input type="checkbox" id="chckActive" name="chckActive">
        </div>
    </div>
    <div class="control-group last">
        <div class="control">
                <button class="btn-admin" type="submit">Registrar</button>
        </div>
    </div>
</div>