<div id="main-slider">
    <div data-id="home" class="slide-main ">
        <?php  echo $this->partial('_partial/_businessman.phtml', $this)?>
    </div>
    <div data-id="product" class="slide-main fix">
        <?php echo $this->partial('_partial/_products.phtml', $this)?>
    </div>
    <div data-id="oportunity" class="slide-main fix">
        <?php echo $this->partial('_partial/_oportunity.phtml', $this)?>
    </div>
    <div data-id="company" class="slide-main fix">
        <?php echo $this->partial('_partial/_company.phtml', $this)?>
    </div>
    <div data-id="contact" class="slide-main">
        <?php echo $this->partial('_partial/_contact.phtml', $this)?>
    </div>
</div>